### PR TITLE
Update requirements and default to GCC 4.7

### PR DESCRIPTION
**Pull request by gbraad**

### CODE REVIEW

**Comment by simonjohansson** [comment]
Great, thanks! Could you just remove the trailing white space and I'll merge this :)

**Comment by gbraad** [comment]
I had noticed them... Will push this later today (on my way back home)

On Thu, Oct 15, 2015 at 4:57 PM, Simon Johansson <notifications@github.com>
wrote:

> Great, thanks! Could you just remove the trailing white space and I'll
> merge this :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simonjohansson/B2G-build/pull/4#issuecomment-148322646>
> .
>



-- 
Gerard Braad — 吉拉德
   F/OSS & IT Consultant in Beijing
   http://gbraad.nl  gpg: 0x592CFE75

**Comment by gbraad** [comment]
*ding*

**Comment by simonjohansson** [comment]
dong.

Thanks!

**Comment by gbraad** [comment]
Great! Sorry I modified the original message instead of adding a new message for 'Fixed'. Has a new image been pushed to docker hub? I had done on my name, but it seems the image got broken in the process (bad connectivity) as a pull does not succeed.

**Comment by simonjohansson** [comment]
@gbraad yeah, it seems like the merge triggered a new build.

https://hub.docker.com/r/simonjohansson/b2g-build/builds/

You still have issues pulling it?

**Pull request merged**
